import { ColumnNames } from './interface';

export const mockColumnNames: ColumnNames = {
  sourceNameField: 'sourceName',
  sourceSeriesField: 'sourceSeries',
  sourceImageField: '',
  targetNameField: 'targetName',
  targetSeriesField: 'targetSeries',
  targetImageField: '',
  weightField: 'weight',
};

export const mockItems = [
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 32,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "WATTO",
    targetSeries: "WATTO",
    weight: 5,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 22,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 41,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "SEBULBA",
    targetSeries: "SEBULBA",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 12,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "JIRA",
    targetSeries: "JIRA",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "SHMI",
    targetSeries: "SHMI",
    weight: 8,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 11,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "KITSTER",
    targetSeries: "KITSTER",
    weight: 3,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "WALD",
    targetSeries: "WALD",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 47,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "JABBA",
    targetSeries: "JABBA",
    weight: 1,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "GREEDO",
    targetSeries: "GREEDO",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN PANAKA",
    sourceSeries: "CAPTAIN PANAKA",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "RIC OLIE",
    targetSeries: "RIC OLIE",
    weight: 4,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "MACE WINDU",
    targetSeries: "MACE WINDU",
    weight: 9,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "KI-ADI-MUNDI",
    targetSeries: "KI-ADI-MUNDI",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 9,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "RABE",
    targetSeries: "RABE",
    weight: 1,
  },
  {
    sourceName: "BOSS NASS",
    sourceSeries: "BOSS NASS",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 1,
  },
  {
    sourceName: "BRAVO TWO",
    sourceSeries: "BRAVO TWO",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 2,
  },
  {
    sourceName: "BRAVO THREE",
    sourceSeries: "BRAVO THREE",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN TYPHO",
    sourceSeries: "CAPTAIN TYPHO",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 3,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "SIO BIBBLE",
    targetSeries: "SIO BIBBLE",
    weight: 1,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "SOLA",
    targetSeries: "SOLA",
    weight: 1,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "JOBAL",
    targetSeries: "JOBAL",
    weight: 1,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "RUWEE",
    targetSeries: "RUWEE",
    weight: 3,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "OWEN",
    targetSeries: "OWEN",
    weight: 3,
  },
  {
    sourceName: "BERU",
    sourceSeries: "BERU",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 1,
  },
  {
    sourceName: "CLIEGG",
    sourceSeries: "CLIEGG",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "SUN RIT",
    targetSeries: "SUN RIT",
    weight: 1,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "POGGLE",
    targetSeries: "POGGLE",
    weight: 1,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "NUTE GUNRAY",
    targetSeries: "NUTE GUNRAY",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 3,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "ODD BALL",
    targetSeries: "ODD BALL",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "EMPEROR",
    targetSeries: "EMPEROR",
    weight: 21,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "GENERAL GRIEVOUS",
    targetSeries: "GENERAL GRIEVOUS",
    weight: 1,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 2,
  },
  {
    sourceName: "CLONE COMMANDER CODY",
    sourceSeries: "CLONE COMMANDER CODY",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 1,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "MOTTI",
    targetSeries: "MOTTI",
    weight: 1,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "TARKIN",
    targetSeries: "TARKIN",
    weight: 7,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "PIETT",
    targetSeries: "PIETT",
    weight: 8,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "OZZEL",
    targetSeries: "OZZEL",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "NEEDA",
    targetSeries: "NEEDA",
    weight: 1,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "DARTH VADER",
    targetSeries: "DARTH VADER",
    weight: 3,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "LANDO",
    targetSeries: "LANDO",
    weight: 4,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 2,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 8,
  },
  {
    sourceName: "DARTH VADER",
    sourceSeries: "DARTH VADER",
    targetName: "JERJERROD",
    targetSeries: "JERJERROD",
    weight: 1,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 17,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 2,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "CHEWBACCA",
    targetSeries: "CHEWBACCA",
    weight: 8,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 28,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 24,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 13,
  },
  {
    sourceName: "R2-D2",
    sourceSeries: "R2-D2",
    targetName: "WATTO",
    targetSeries: "WATTO",
    weight: 3,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 55,
  },
  {
    sourceName: "KITSTER",
    sourceSeries: "KITSTER",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 2,
  },
  {
    sourceName: "JABBA",
    sourceSeries: "JABBA",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 4,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 5,
  },
  {
    sourceName: "CAPTAIN TYPHO",
    sourceSeries: "CAPTAIN TYPHO",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 1,
  },
  {
    sourceName: "BERU",
    sourceSeries: "BERU",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 1,
  },
  {
    sourceName: "OWEN",
    sourceSeries: "OWEN",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 2,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 3,
  },
  {
    sourceName: "R2-D2",
    sourceSeries: "R2-D2",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 5,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 34,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 23,
  },
  {
    sourceName: "CAPTAIN ANTILLES",
    sourceSeries: "CAPTAIN ANTILLES",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 1,
  },
  {
    sourceName: "BIGGS",
    sourceSeries: "BIGGS",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 18,
  },
  {
    sourceName: "LANDO",
    sourceSeries: "LANDO",
    targetName: "R2-D2",
    targetSeries: "R2-D2",
    weight: 5,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 6,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "CHEWBACCA",
    targetSeries: "CHEWBACCA",
    weight: 39,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 32,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 77,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "JABBA",
    targetSeries: "JABBA",
    weight: 3,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 48,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "RIEEKAN",
    targetSeries: "RIEEKAN",
    weight: 1,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "LANDO",
    targetSeries: "LANDO",
    weight: 20,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "CHEWBACCA",
    targetSeries: "CHEWBACCA",
    weight: 2,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "FINN",
    targetSeries: "FINN",
    weight: 20,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "REY",
    targetSeries: "REY",
    weight: 13,
  },
  {
    sourceName: "BALA-TIK",
    sourceSeries: "BALA-TIK",
    targetName: "CHEWBACCA",
    targetSeries: "CHEWBACCA",
    weight: 1,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "MAZ",
    targetSeries: "MAZ",
    weight: 2,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "POE",
    targetSeries: "POE",
    weight: 2,
  },
  {
    sourceName: "CHEWBACCA",
    sourceSeries: "CHEWBACCA",
    targetName: "KYLO REN",
    targetSeries: "KYLO REN",
    weight: 3,
  },
  {
    sourceName: "CAPTAIN PHASMA",
    sourceSeries: "CAPTAIN PHASMA",
    targetName: "CHEWBACCA",
    targetSeries: "CHEWBACCA",
    weight: 1,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "POE",
    targetSeries: "POE",
    weight: 8,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "LOR SAN TEKKA",
    targetSeries: "LOR SAN TEKKA",
    weight: 2,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "REY",
    targetSeries: "REY",
    weight: 17,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "UNKAR PLUTT",
    targetSeries: "UNKAR PLUTT",
    weight: 1,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "FINN",
    targetSeries: "FINN",
    weight: 15,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 9,
  },
  {
    sourceName: "BALA-TIK",
    sourceSeries: "BALA-TIK",
    targetName: "BB-8",
    targetSeries: "BB-8",
    weight: 1,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "MAZ",
    targetSeries: "MAZ",
    weight: 3,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 3,
  },
  {
    sourceName: "BB-8",
    sourceSeries: "BB-8",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 3,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 1,
  },
  {
    sourceName: "PK-4",
    sourceSeries: "PK-4",
    targetName: "TC-14",
    targetSeries: "TC-14",
    weight: 1,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "TC-14",
    targetSeries: "TC-14",
    weight: 1,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "TC-14",
    targetSeries: "TC-14",
    weight: 1,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 26,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "TC-14",
    targetSeries: "TC-14",
    weight: 1,
  },
  {
    sourceName: "DOFINE",
    sourceSeries: "DOFINE",
    targetName: "NUTE GUNRAY",
    targetSeries: "NUTE GUNRAY",
    weight: 1,
  },
  {
    sourceName: "DOFINE",
    sourceSeries: "DOFINE",
    targetName: "TC-14",
    targetSeries: "TC-14",
    weight: 1,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "RUNE",
    targetSeries: "RUNE",
    weight: 8,
  },
  {
    sourceName: "RUNE",
    sourceSeries: "RUNE",
    targetName: "TEY HOW",
    targetSeries: "TEY HOW",
    weight: 2,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "TEY HOW",
    targetSeries: "TEY HOW",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN PANAKA",
    sourceSeries: "CAPTAIN PANAKA",
    targetName: "EMPEROR",
    targetSeries: "EMPEROR",
    weight: 3,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "SIO BIBBLE",
    targetSeries: "SIO BIBBLE",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN PANAKA",
    sourceSeries: "CAPTAIN PANAKA",
    targetName: "SIO BIBBLE",
    targetSeries: "SIO BIBBLE",
    weight: 3,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 22,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 15,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "TARPALS",
    targetSeries: "TARPALS",
    weight: 2,
  },
  {
    sourceName: "BOSS NASS",
    sourceSeries: "BOSS NASS",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 2,
  },
  {
    sourceName: "BOSS NASS",
    sourceSeries: "BOSS NASS",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 2,
  },
  {
    sourceName: "BOSS NASS",
    sourceSeries: "BOSS NASS",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 2,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "NUTE GUNRAY",
    targetSeries: "NUTE GUNRAY",
    weight: 6,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "RUNE",
    targetSeries: "RUNE",
    weight: 3,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "SIO BIBBLE",
    targetSeries: "SIO BIBBLE",
    weight: 2,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "SIO BIBBLE",
    targetSeries: "SIO BIBBLE",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN PANAKA",
    sourceSeries: "CAPTAIN PANAKA",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 7,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "SIO BIBBLE",
    targetSeries: "SIO BIBBLE",
    weight: 2,
  },
  {
    sourceName: "CAPTAIN PANAKA",
    sourceSeries: "CAPTAIN PANAKA",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 9,
  },
  {
    sourceName: "CAPTAIN PANAKA",
    sourceSeries: "CAPTAIN PANAKA",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 7,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 16,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "SIO BIBBLE",
    targetSeries: "SIO BIBBLE",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN PANAKA",
    sourceSeries: "CAPTAIN PANAKA",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 7,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "RIC OLIE",
    targetSeries: "RIC OLIE",
    weight: 3,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "RIC OLIE",
    targetSeries: "RIC OLIE",
    weight: 1,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "RIC OLIE",
    targetSeries: "RIC OLIE",
    weight: 2,
  },
  {
    sourceName: "CAPTAIN PANAKA",
    sourceSeries: "CAPTAIN PANAKA",
    targetName: "RIC OLIE",
    targetSeries: "RIC OLIE",
    weight: 2,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 10,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "WATTO",
    targetSeries: "WATTO",
    weight: 6,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "WATTO",
    targetSeries: "WATTO",
    weight: 3,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "SEBULBA",
    targetSeries: "SEBULBA",
    weight: 2,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "SEBULBA",
    targetSeries: "SEBULBA",
    weight: 2,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "SEBULBA",
    targetSeries: "SEBULBA",
    weight: 2,
  },
  {
    sourceName: "JIRA",
    sourceSeries: "JIRA",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 2,
  },
  {
    sourceName: "JIRA",
    sourceSeries: "JIRA",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 1,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "SHMI",
    targetSeries: "SHMI",
    weight: 3,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "SHMI",
    targetSeries: "SHMI",
    weight: 8,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "SHMI",
    targetSeries: "SHMI",
    weight: 5,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 12,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "SIO BIBBLE",
    targetSeries: "SIO BIBBLE",
    weight: 1,
  },
  {
    sourceName: "DARTH MAUL",
    sourceSeries: "DARTH MAUL",
    targetName: "EMPEROR",
    targetSeries: "EMPEROR",
    weight: 3,
  },
  {
    sourceName: "KITSTER",
    sourceSeries: "KITSTER",
    targetName: "WALD",
    targetSeries: "WALD",
    weight: 1,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "KITSTER",
    targetSeries: "KITSTER",
    weight: 1,
  },
  {
    sourceName: "KITSTER",
    sourceSeries: "KITSTER",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 2,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "WALD",
    targetSeries: "WALD",
    weight: 1,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "WALD",
    targetSeries: "WALD",
    weight: 2,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "SHMI",
    targetSeries: "SHMI",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "WATTO",
    targetSeries: "WATTO",
    weight: 1,
  },
  {
    sourceName: "KITSTER",
    sourceSeries: "KITSTER",
    targetName: "WATTO",
    targetSeries: "WATTO",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "KITSTER",
    targetSeries: "KITSTER",
    weight: 1,
  },
  {
    sourceName: "KITSTER",
    sourceSeries: "KITSTER",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 1,
  },
  {
    sourceName: "FODE/BEED",
    sourceSeries: "FODE/BEED",
    targetName: "JABBA",
    targetSeries: "JABBA",
    weight: 1,
  },
  {
    sourceName: "JABBA",
    sourceSeries: "JABBA",
    targetName: "SHMI",
    targetSeries: "SHMI",
    weight: 1,
  },
  {
    sourceName: "SEBULBA",
    sourceSeries: "SEBULBA",
    targetName: "SHMI",
    targetSeries: "SHMI",
    weight: 1,
  },
  {
    sourceName: "JABBA",
    sourceSeries: "JABBA",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 1,
  },
  {
    sourceName: "JABBA",
    sourceSeries: "JABBA",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 1,
  },
  {
    sourceName: "JABBA",
    sourceSeries: "JABBA",
    targetName: "SEBULBA",
    targetSeries: "SEBULBA",
    weight: 1,
  },
  {
    sourceName: "JABBA",
    sourceSeries: "JABBA",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 1,
  },
  {
    sourceName: "FODE/BEED",
    sourceSeries: "FODE/BEED",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 2,
  },
  {
    sourceName: "FODE/BEED",
    sourceSeries: "FODE/BEED",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 1,
  },
  {
    sourceName: "GREEDO",
    sourceSeries: "GREEDO",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 1,
  },
  {
    sourceName: "GREEDO",
    sourceSeries: "GREEDO",
    targetName: "WALD",
    targetSeries: "WALD",
    weight: 1,
  },
  {
    sourceName: "KITSTER",
    sourceSeries: "KITSTER",
    targetName: "SHMI",
    targetSeries: "SHMI",
    weight: 1,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "VALORUM",
    targetSeries: "VALORUM",
    weight: 2,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 5,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 1,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "VALORUM",
    targetSeries: "VALORUM",
    weight: 1,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "VALORUM",
    targetSeries: "VALORUM",
    weight: 1,
  },
  {
    sourceName: "MACE WINDU",
    sourceSeries: "MACE WINDU",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 2,
  },
  {
    sourceName: "KI-ADI-MUNDI",
    sourceSeries: "KI-ADI-MUNDI",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 2,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 3,
  },
  {
    sourceName: "QUI-GON",
    sourceSeries: "QUI-GON",
    targetName: "RABE",
    targetSeries: "RABE",
    weight: 1,
  },
  {
    sourceName: "KI-ADI-MUNDI",
    sourceSeries: "KI-ADI-MUNDI",
    targetName: "MACE WINDU",
    targetSeries: "MACE WINDU",
    weight: 4,
  },
  {
    sourceName: "MACE WINDU",
    sourceSeries: "MACE WINDU",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 16,
  },
  {
    sourceName: "MACE WINDU",
    sourceSeries: "MACE WINDU",
    targetName: "RABE",
    targetSeries: "RABE",
    weight: 1,
  },
  {
    sourceName: "KI-ADI-MUNDI",
    sourceSeries: "KI-ADI-MUNDI",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 4,
  },
  {
    sourceName: "KI-ADI-MUNDI",
    sourceSeries: "KI-ADI-MUNDI",
    targetName: "RABE",
    targetSeries: "RABE",
    weight: 1,
  },
  {
    sourceName: "RABE",
    sourceSeries: "RABE",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 1,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "EMPEROR",
    targetSeries: "EMPEROR",
    weight: 6,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "VALORUM",
    targetSeries: "VALORUM",
    weight: 1,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 20,
  },
  {
    sourceName: "MACE WINDU",
    sourceSeries: "MACE WINDU",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 9,
  },
  {
    sourceName: "KI-ADI-MUNDI",
    sourceSeries: "KI-ADI-MUNDI",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 1,
  },
  {
    sourceName: "BOSS NASS",
    sourceSeries: "BOSS NASS",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 2,
  },
  {
    sourceName: "DARTH MAUL",
    sourceSeries: "DARTH MAUL",
    targetName: "NUTE GUNRAY",
    targetSeries: "NUTE GUNRAY",
    weight: 3,
  },
  {
    sourceName: "BOSS NASS",
    sourceSeries: "BOSS NASS",
    targetName: "CAPTAIN PANAKA",
    targetSeries: "CAPTAIN PANAKA",
    weight: 1,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 9,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "GENERAL CEEL",
    targetSeries: "GENERAL CEEL",
    weight: 1,
  },
  {
    sourceName: "GENERAL CEEL",
    sourceSeries: "GENERAL CEEL",
    targetName: "NUTE GUNRAY",
    targetSeries: "NUTE GUNRAY",
    weight: 1,
  },
  {
    sourceName: "DARTH MAUL",
    sourceSeries: "DARTH MAUL",
    targetName: "GENERAL CEEL",
    targetSeries: "GENERAL CEEL",
    weight: 1,
  },
  {
    sourceName: "DARTH MAUL",
    sourceSeries: "DARTH MAUL",
    targetName: "RUNE",
    targetSeries: "RUNE",
    weight: 1,
  },
  {
    sourceName: "BRAVO TWO",
    sourceSeries: "BRAVO TWO",
    targetName: "RIC OLIE",
    targetSeries: "RIC OLIE",
    weight: 4,
  },
  {
    sourceName: "GENERAL CEEL",
    sourceSeries: "GENERAL CEEL",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 1,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 2,
  },
  {
    sourceName: "DOFINE",
    sourceSeries: "DOFINE",
    targetName: "TEY HOW",
    targetSeries: "TEY HOW",
    weight: 1,
  },
  {
    sourceName: "BRAVO THREE",
    sourceSeries: "BRAVO THREE",
    targetName: "BRAVO TWO",
    targetSeries: "BRAVO TWO",
    weight: 2,
  },
  {
    sourceName: "BRAVO THREE",
    sourceSeries: "BRAVO THREE",
    targetName: "RIC OLIE",
    targetSeries: "RIC OLIE",
    weight: 2,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 5,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "SENATOR ASK AAK",
    targetSeries: "SENATOR ASK AAK",
    weight: 2,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "ORN FREE TAA",
    targetSeries: "ORN FREE TAA",
    weight: 2,
  },
  {
    sourceName: "ORN FREE TAA",
    sourceSeries: "ORN FREE TAA",
    targetName: "SENATOR ASK AAK",
    targetSeries: "SENATOR ASK AAK",
    weight: 1,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "MACE WINDU",
    targetSeries: "MACE WINDU",
    weight: 3,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 2,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "KI-ADI-MUNDI",
    targetSeries: "KI-ADI-MUNDI",
    weight: 1,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "MACE WINDU",
    targetSeries: "MACE WINDU",
    weight: 2,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 8,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "KI-ADI-MUNDI",
    targetSeries: "KI-ADI-MUNDI",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN TYPHO",
    sourceSeries: "CAPTAIN TYPHO",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN TYPHO",
    sourceSeries: "CAPTAIN TYPHO",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 2,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "PK-4",
    targetSeries: "PK-4",
    weight: 1,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "SOLA",
    targetSeries: "SOLA",
    weight: 1,
  },
  {
    sourceName: "JOBAL",
    sourceSeries: "JOBAL",
    targetName: "SOLA",
    targetSeries: "SOLA",
    weight: 2,
  },
  {
    sourceName: "RUWEE",
    sourceSeries: "RUWEE",
    targetName: "SOLA",
    targetSeries: "SOLA",
    weight: 1,
  },
  {
    sourceName: "JOBAL",
    sourceSeries: "JOBAL",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 1,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "RUWEE",
    targetSeries: "RUWEE",
    weight: 1,
  },
  {
    sourceName: "JOBAL",
    sourceSeries: "JOBAL",
    targetName: "RUWEE",
    targetSeries: "RUWEE",
    weight: 1,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "TAUN WE",
    targetSeries: "TAUN WE",
    weight: 5,
  },
  {
    sourceName: "LAMA SU",
    sourceSeries: "LAMA SU",
    targetName: "TAUN WE",
    targetSeries: "TAUN WE",
    weight: 2,
  },
  {
    sourceName: "LAMA SU",
    sourceSeries: "LAMA SU",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 6,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "TAUN WE",
    targetSeries: "TAUN WE",
    weight: 2,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "JANGO FETT",
    targetSeries: "JANGO FETT",
    weight: 3,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 1,
  },
  {
    sourceName: "JANGO FETT",
    sourceSeries: "JANGO FETT",
    targetName: "TAUN WE",
    targetSeries: "TAUN WE",
    weight: 1,
  },
  {
    sourceName: "JANGO FETT",
    sourceSeries: "JANGO FETT",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "OWEN",
    targetSeries: "OWEN",
    weight: 4,
  },
  {
    sourceName: "BERU",
    sourceSeries: "BERU",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 3,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "CLIEGG",
    targetSeries: "CLIEGG",
    weight: 1,
  },
  {
    sourceName: "BERU",
    sourceSeries: "BERU",
    targetName: "OWEN",
    targetSeries: "OWEN",
    weight: 4,
  },
  {
    sourceName: "OWEN",
    sourceSeries: "OWEN",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 4,
  },
  {
    sourceName: "CLIEGG",
    sourceSeries: "CLIEGG",
    targetName: "OWEN",
    targetSeries: "OWEN",
    weight: 2,
  },
  {
    sourceName: "BERU",
    sourceSeries: "BERU",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 1,
  },
  {
    sourceName: "BERU",
    sourceSeries: "BERU",
    targetName: "CLIEGG",
    targetSeries: "CLIEGG",
    weight: 1,
  },
  {
    sourceName: "CLIEGG",
    sourceSeries: "CLIEGG",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 2,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 8,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 5,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "SENATOR ASK AAK",
    targetSeries: "SENATOR ASK AAK",
    weight: 1,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "SENATOR ASK AAK",
    targetSeries: "SENATOR ASK AAK",
    weight: 1,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "JAR JAR",
    targetSeries: "JAR JAR",
    weight: 1,
  },
  {
    sourceName: "SENATOR ASK AAK",
    sourceSeries: "SENATOR ASK AAK",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 1,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 1,
  },
  {
    sourceName: "MACE WINDU",
    sourceSeries: "MACE WINDU",
    targetName: "SENATOR ASK AAK",
    targetSeries: "SENATOR ASK AAK",
    weight: 1,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "MACE WINDU",
    targetSeries: "MACE WINDU",
    weight: 1,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "SENATOR ASK AAK",
    targetSeries: "SENATOR ASK AAK",
    weight: 1,
  },
  {
    sourceName: "MACE WINDU",
    sourceSeries: "MACE WINDU",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 2,
  },
  {
    sourceName: "JAR JAR",
    sourceSeries: "JAR JAR",
    targetName: "ORN FREE TAA",
    targetSeries: "ORN FREE TAA",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 3,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "JANGO FETT",
    targetSeries: "JANGO FETT",
    weight: 1,
  },
  {
    sourceName: "POGGLE",
    sourceSeries: "POGGLE",
    targetName: "SUN RIT",
    targetSeries: "SUN RIT",
    weight: 2,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "SUN RIT",
    targetSeries: "SUN RIT",
    weight: 2,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "POGGLE",
    targetSeries: "POGGLE",
    weight: 2,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "SUN RIT",
    targetSeries: "SUN RIT",
    weight: 1,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "POGGLE",
    targetSeries: "POGGLE",
    weight: 1,
  },
  {
    sourceName: "NUTE GUNRAY",
    sourceSeries: "NUTE GUNRAY",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 3,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "SUN RIT",
    targetSeries: "SUN RIT",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "SUN RIT",
    targetSeries: "SUN RIT",
    weight: 1,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "POGGLE",
    targetSeries: "POGGLE",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "POGGLE",
    targetSeries: "POGGLE",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "NUTE GUNRAY",
    targetSeries: "NUTE GUNRAY",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "MACE WINDU",
    targetSeries: "MACE WINDU",
    weight: 2,
  },
  {
    sourceName: "KI-ADI-MUNDI",
    sourceSeries: "KI-ADI-MUNDI",
    targetName: "PLO KOON",
    targetSeries: "PLO KOON",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 2,
  },
  {
    sourceName: "PADME",
    sourceSeries: "PADME",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 1,
  },
  {
    sourceName: "COUNT DOOKU",
    sourceSeries: "COUNT DOOKU",
    targetName: "EMPEROR",
    targetSeries: "EMPEROR",
    weight: 2,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "ODD BALL",
    targetSeries: "ODD BALL",
    weight: 2,
  },
  {
    sourceName: "GENERAL GRIEVOUS",
    sourceSeries: "GENERAL GRIEVOUS",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 2,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 9,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "EMPEROR",
    targetSeries: "EMPEROR",
    weight: 2,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 3,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 5,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "FANG ZAR",
    targetSeries: "FANG ZAR",
    weight: 2,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 2,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "GIDDEAN DANU",
    targetSeries: "GIDDEAN DANU",
    weight: 1,
  },
  {
    sourceName: "FANG ZAR",
    sourceSeries: "FANG ZAR",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 2,
  },
  {
    sourceName: "FANG ZAR",
    sourceSeries: "FANG ZAR",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 2,
  },
  {
    sourceName: "FANG ZAR",
    sourceSeries: "FANG ZAR",
    targetName: "GIDDEAN DANU",
    targetSeries: "GIDDEAN DANU",
    weight: 1,
  },
  {
    sourceName: "MON MOTHMA",
    sourceSeries: "MON MOTHMA",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 2,
  },
  {
    sourceName: "GIDDEAN DANU",
    sourceSeries: "GIDDEAN DANU",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 1,
  },
  {
    sourceName: "GIDDEAN DANU",
    sourceSeries: "GIDDEAN DANU",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN TYPHO",
    sourceSeries: "CAPTAIN TYPHO",
    targetName: "PADME",
    targetSeries: "PADME",
    weight: 2,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "CAPTAIN TYPHO",
    targetSeries: "CAPTAIN TYPHO",
    weight: 2,
  },
  {
    sourceName: "CLONE COMMANDER GREE",
    sourceSeries: "CLONE COMMANDER GREE",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 1,
  },
  {
    sourceName: "CLONE COMMANDER CODY",
    sourceSeries: "CLONE COMMANDER CODY",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 2,
  },
  {
    sourceName: "OBI-WAN",
    sourceSeries: "OBI-WAN",
    targetName: "TION MEDON",
    targetSeries: "TION MEDON",
    weight: 1,
  },
  {
    sourceName: "GENERAL GRIEVOUS",
    sourceSeries: "GENERAL GRIEVOUS",
    targetName: "NUTE GUNRAY",
    targetSeries: "NUTE GUNRAY",
    weight: 1,
  },
  {
    sourceName: "CLONE COMMANDER CODY",
    sourceSeries: "CLONE COMMANDER CODY",
    targetName: "MACE WINDU",
    targetSeries: "MACE WINDU",
    weight: 1,
  },
  {
    sourceName: "CLONE COMMANDER CODY",
    sourceSeries: "CLONE COMMANDER CODY",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 1,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "CAPTAIN ANTILLES",
    targetSeries: "CAPTAIN ANTILLES",
    weight: 2,
  },
  {
    sourceName: "BAIL ORGANA",
    sourceSeries: "BAIL ORGANA",
    targetName: "QUI-GON",
    targetSeries: "QUI-GON",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "CAPTAIN ANTILLES",
    targetSeries: "CAPTAIN ANTILLES",
    weight: 1,
  },
  {
    sourceName: "CAMIE",
    sourceSeries: "CAMIE",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 2,
  },
  {
    sourceName: "BIGGS",
    sourceSeries: "BIGGS",
    targetName: "CAMIE",
    targetSeries: "CAMIE",
    weight: 2,
  },
  {
    sourceName: "BIGGS",
    sourceSeries: "BIGGS",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 4,
  },
  {
    sourceName: "BERU",
    sourceSeries: "BERU",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 3,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "OWEN",
    targetSeries: "OWEN",
    weight: 3,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 29,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 49,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 26,
  },
  {
    sourceName: "BERU",
    sourceSeries: "BERU",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 1,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 22,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 1,
  },
  {
    sourceName: "MOTTI",
    sourceSeries: "MOTTI",
    targetName: "TARKIN",
    targetSeries: "TARKIN",
    weight: 2,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "OBI-WAN",
    targetSeries: "OBI-WAN",
    weight: 10,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 43,
  },
  {
    sourceName: "GREEDO",
    sourceSeries: "GREEDO",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "JABBA",
    targetSeries: "JABBA",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 54,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "MOTTI",
    targetSeries: "MOTTI",
    weight: 1,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "TARKIN",
    targetSeries: "TARKIN",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 69,
  },
  {
    sourceName: "DODONNA",
    sourceSeries: "DODONNA",
    targetName: "GOLD LEADER",
    targetSeries: "GOLD LEADER",
    weight: 1,
  },
  {
    sourceName: "DODONNA",
    sourceSeries: "DODONNA",
    targetName: "WEDGE",
    targetSeries: "WEDGE",
    weight: 1,
  },
  {
    sourceName: "DODONNA",
    sourceSeries: "DODONNA",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 1,
  },
  {
    sourceName: "GOLD LEADER",
    sourceSeries: "GOLD LEADER",
    targetName: "WEDGE",
    targetSeries: "WEDGE",
    weight: 1,
  },
  {
    sourceName: "GOLD LEADER",
    sourceSeries: "GOLD LEADER",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 1,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "WEDGE",
    targetSeries: "WEDGE",
    weight: 4,
  },
  {
    sourceName: "BIGGS",
    sourceSeries: "BIGGS",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 1,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "RED LEADER",
    targetSeries: "RED LEADER",
    weight: 1,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "RED LEADER",
    targetSeries: "RED LEADER",
    weight: 3,
  },
  {
    sourceName: "BIGGS",
    sourceSeries: "BIGGS",
    targetName: "RED LEADER",
    targetSeries: "RED LEADER",
    weight: 3,
  },
  {
    sourceName: "BIGGS",
    sourceSeries: "BIGGS",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "RED LEADER",
    targetSeries: "RED LEADER",
    weight: 1,
  },
  {
    sourceName: "RED LEADER",
    sourceSeries: "RED LEADER",
    targetName: "WEDGE",
    targetSeries: "WEDGE",
    weight: 3,
  },
  {
    sourceName: "GOLD LEADER",
    sourceSeries: "GOLD LEADER",
    targetName: "RED LEADER",
    targetSeries: "RED LEADER",
    weight: 1,
  },
  {
    sourceName: "BIGGS",
    sourceSeries: "BIGGS",
    targetName: "WEDGE",
    targetSeries: "WEDGE",
    weight: 2,
  },
  {
    sourceName: "RED LEADER",
    sourceSeries: "RED LEADER",
    targetName: "RED TEN",
    targetSeries: "RED TEN",
    weight: 1,
  },
  {
    sourceName: "BIGGS",
    sourceSeries: "BIGGS",
    targetName: "GOLD LEADER",
    targetSeries: "GOLD LEADER",
    weight: 1,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "RED TEN",
    targetSeries: "RED TEN",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "RIEEKAN",
    targetSeries: "RIEEKAN",
    weight: 3,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "RIEEKAN",
    targetSeries: "RIEEKAN",
    weight: 4,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "DERLIN",
    targetSeries: "DERLIN",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "ZEV",
    targetSeries: "ZEV",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "RIEEKAN",
    targetSeries: "RIEEKAN",
    weight: 1,
  },
  {
    sourceName: "OZZEL",
    sourceSeries: "OZZEL",
    targetName: "PIETT",
    targetSeries: "PIETT",
    weight: 2,
  },
  {
    sourceName: "DERLIN",
    sourceSeries: "DERLIN",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 1,
  },
  {
    sourceName: "DACK",
    sourceSeries: "DACK",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 3,
  },
  {
    sourceName: "JANSON",
    sourceSeries: "JANSON",
    targetName: "WEDGE",
    targetSeries: "WEDGE",
    weight: 2,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "ZEV",
    targetSeries: "ZEV",
    weight: 1,
  },
  {
    sourceName: "NEEDA",
    sourceSeries: "NEEDA",
    targetName: "PIETT",
    targetSeries: "PIETT",
    weight: 1,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "YODA",
    targetSeries: "YODA",
    weight: 6,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "PIETT",
    targetSeries: "PIETT",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "LANDO",
    targetSeries: "LANDO",
    weight: 12,
  },
  {
    sourceName: "LANDO",
    sourceSeries: "LANDO",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 12,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "LANDO",
    targetSeries: "LANDO",
    weight: 8,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "LANDO",
    targetSeries: "LANDO",
    weight: 2,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 1,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 1,
  },
  {
    sourceName: "BOBA FETT",
    sourceSeries: "BOBA FETT",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 1,
  },
  {
    sourceName: "LANDO",
    sourceSeries: "LANDO",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 6,
  },
  {
    sourceName: "BIB FORTUNA",
    sourceSeries: "BIB FORTUNA",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 2,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "JABBA",
    targetSeries: "JABBA",
    weight: 3,
  },
  {
    sourceName: "JABBA",
    sourceSeries: "JABBA",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 2,
  },
  {
    sourceName: "BOUSHH",
    sourceSeries: "BOUSHH",
    targetName: "JABBA",
    targetSeries: "JABBA",
    weight: 1,
  },
  {
    sourceName: "BOUSHH",
    sourceSeries: "BOUSHH",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 2,
  },
  {
    sourceName: "BOUSHH",
    sourceSeries: "BOUSHH",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 1,
  },
  {
    sourceName: "BOUSHH",
    sourceSeries: "BOUSHH",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 1,
  },
  {
    sourceName: "BIB FORTUNA",
    sourceSeries: "BIB FORTUNA",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 1,
  },
  {
    sourceName: "BIB FORTUNA",
    sourceSeries: "BIB FORTUNA",
    targetName: "JABBA",
    targetSeries: "JABBA",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 2,
  },
  {
    sourceName: "LANDO",
    sourceSeries: "LANDO",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "LANDO",
    targetSeries: "LANDO",
    weight: 5,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 1,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 1,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "MON MOTHMA",
    targetSeries: "MON MOTHMA",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 2,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 2,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 1,
  },
  {
    sourceName: "EMPEROR",
    sourceSeries: "EMPEROR",
    targetName: "LUKE",
    targetSeries: "LUKE",
    weight: 3,
  },
  {
    sourceName: "LANDO",
    sourceSeries: "LANDO",
    targetName: "WEDGE",
    targetSeries: "WEDGE",
    weight: 6,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "WEDGE",
    targetSeries: "WEDGE",
    weight: 1,
  },
  {
    sourceName: "LOR SAN TEKKA",
    sourceSeries: "LOR SAN TEKKA",
    targetName: "POE",
    targetSeries: "POE",
    weight: 3,
  },
  {
    sourceName: "KYLO REN",
    sourceSeries: "KYLO REN",
    targetName: "LOR SAN TEKKA",
    targetSeries: "LOR SAN TEKKA",
    weight: 1,
  },
  {
    sourceName: "KYLO REN",
    sourceSeries: "KYLO REN",
    targetName: "POE",
    targetSeries: "POE",
    weight: 2,
  },
  {
    sourceName: "CAPTAIN PHASMA",
    sourceSeries: "CAPTAIN PHASMA",
    targetName: "KYLO REN",
    targetSeries: "KYLO REN",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN PHASMA",
    sourceSeries: "CAPTAIN PHASMA",
    targetName: "LOR SAN TEKKA",
    targetSeries: "LOR SAN TEKKA",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN PHASMA",
    sourceSeries: "CAPTAIN PHASMA",
    targetName: "POE",
    targetSeries: "POE",
    weight: 1,
  },
  {
    sourceName: "CAPTAIN PHASMA",
    sourceSeries: "CAPTAIN PHASMA",
    targetName: "FINN",
    targetSeries: "FINN",
    weight: 3,
  },
  {
    sourceName: "GENERAL HUX",
    sourceSeries: "GENERAL HUX",
    targetName: "KYLO REN",
    targetSeries: "KYLO REN",
    weight: 5,
  },
  {
    sourceName: "REY",
    sourceSeries: "REY",
    targetName: "UNKAR PLUTT",
    targetSeries: "UNKAR PLUTT",
    weight: 2,
  },
  {
    sourceName: "FINN",
    sourceSeries: "FINN",
    targetName: "POE",
    targetSeries: "POE",
    weight: 11,
  },
  {
    sourceName: "GENERAL HUX",
    sourceSeries: "GENERAL HUX",
    targetName: "LIEUTENANT MITAKA",
    targetSeries: "LIEUTENANT MITAKA",
    weight: 1,
  },
  {
    sourceName: "KYLO REN",
    sourceSeries: "KYLO REN",
    targetName: "LIEUTENANT MITAKA",
    targetSeries: "LIEUTENANT MITAKA",
    weight: 2,
  },
  {
    sourceName: "CAPTAIN PHASMA",
    sourceSeries: "CAPTAIN PHASMA",
    targetName: "GENERAL HUX",
    targetSeries: "GENERAL HUX",
    weight: 1,
  },
  {
    sourceName: "FINN",
    sourceSeries: "FINN",
    targetName: "REY",
    targetSeries: "REY",
    weight: 29,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "REY",
    targetSeries: "REY",
    weight: 17,
  },
  {
    sourceName: "FINN",
    sourceSeries: "FINN",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 23,
  },
  {
    sourceName: "BALA-TIK",
    sourceSeries: "BALA-TIK",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 2,
  },
  {
    sourceName: "BALA-TIK",
    sourceSeries: "BALA-TIK",
    targetName: "REY",
    targetSeries: "REY",
    weight: 1,
  },
  {
    sourceName: "BALA-TIK",
    sourceSeries: "BALA-TIK",
    targetName: "FINN",
    targetSeries: "FINN",
    weight: 1,
  },
  {
    sourceName: "GENERAL HUX",
    sourceSeries: "GENERAL HUX",
    targetName: "SNOKE",
    targetSeries: "SNOKE",
    weight: 3,
  },
  {
    sourceName: "KYLO REN",
    sourceSeries: "KYLO REN",
    targetName: "SNOKE",
    targetSeries: "SNOKE",
    weight: 2,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "MAZ",
    targetSeries: "MAZ",
    weight: 4,
  },
  {
    sourceName: "FINN",
    sourceSeries: "FINN",
    targetName: "MAZ",
    targetSeries: "MAZ",
    weight: 2,
  },
  {
    sourceName: "MAZ",
    sourceSeries: "MAZ",
    targetName: "REY",
    targetSeries: "REY",
    weight: 2,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "POE",
    targetSeries: "POE",
    weight: 2,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "POE",
    targetSeries: "POE",
    weight: 3,
  },
  {
    sourceName: "FINN",
    sourceSeries: "FINN",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 3,
  },
  {
    sourceName: "KYLO REN",
    sourceSeries: "KYLO REN",
    targetName: "REY",
    targetSeries: "REY",
    weight: 4,
  },
  {
    sourceName: "POE",
    sourceSeries: "POE",
    targetName: "SNAP",
    targetSeries: "SNAP",
    weight: 2,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "POE",
    targetSeries: "POE",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "POE",
    targetSeries: "POE",
    weight: 2,
  },
  {
    sourceName: "ADMIRAL STATURA",
    sourceSeries: "ADMIRAL STATURA",
    targetName: "POE",
    targetSeries: "POE",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "SNAP",
    targetSeries: "SNAP",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "SNAP",
    targetSeries: "SNAP",
    weight: 1,
  },
  {
    sourceName: "FINN",
    sourceSeries: "FINN",
    targetName: "SNAP",
    targetSeries: "SNAP",
    weight: 1,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "SNAP",
    targetSeries: "SNAP",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "SNAP",
    targetSeries: "SNAP",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL STATURA",
    sourceSeries: "ADMIRAL STATURA",
    targetName: "SNAP",
    targetSeries: "SNAP",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL STATURA",
    sourceSeries: "ADMIRAL STATURA",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "FINN",
    targetSeries: "FINN",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL ACKBAR",
    sourceSeries: "ADMIRAL ACKBAR",
    targetName: "ADMIRAL STATURA",
    targetSeries: "ADMIRAL STATURA",
    weight: 1,
  },
  {
    sourceName: "C-3PO",
    sourceSeries: "C-3PO",
    targetName: "FINN",
    targetSeries: "FINN",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL STATURA",
    sourceSeries: "ADMIRAL STATURA",
    targetName: "FINN",
    targetSeries: "FINN",
    weight: 1,
  },
  {
    sourceName: "ADMIRAL STATURA",
    sourceSeries: "ADMIRAL STATURA",
    targetName: "LEIA",
    targetSeries: "LEIA",
    weight: 2,
  },
  {
    sourceName: "ADMIRAL STATURA",
    sourceSeries: "ADMIRAL STATURA",
    targetName: "C-3PO",
    targetSeries: "C-3PO",
    weight: 2,
  },
  {
    sourceName: "CAPTAIN PHASMA",
    sourceSeries: "CAPTAIN PHASMA",
    targetName: "HAN",
    targetSeries: "HAN",
    weight: 2,
  },
  {
    sourceName: "COLONEL DATOO",
    sourceSeries: "COLONEL DATOO",
    targetName: "GENERAL HUX",
    targetSeries: "GENERAL HUX",
    weight: 1,
  },
  {
    sourceName: "ELLO ASTY",
    sourceSeries: "ELLO ASTY",
    targetName: "POE",
    targetSeries: "POE",
    weight: 3,
  },
  {
    sourceName: "JESS",
    sourceSeries: "JESS",
    targetName: "SNAP",
    targetSeries: "SNAP",
    weight: 1,
  },
  {
    sourceName: "HAN",
    sourceSeries: "HAN",
    targetName: "KYLO REN",
    targetSeries: "KYLO REN",
    weight: 3,
  },
  {
    sourceName: "FINN",
    sourceSeries: "FINN",
    targetName: "KYLO REN",
    targetSeries: "KYLO REN",
    weight: 2,
  },
  {
    sourceName: "JESS",
    sourceSeries: "JESS",
    targetName: "NIV LEK",
    targetSeries: "NIV LEK",
    weight: 2,
  },
  {
    sourceName: "NIV LEK",
    sourceSeries: "NIV LEK",
    targetName: "YOLO ZIFF",
    targetSeries: "YOLO ZIFF",
    weight: 1,
  },
  {
    sourceName: "NIV LEK",
    sourceSeries: "NIV LEK",
    targetName: "POE",
    targetSeries: "POE",
    weight: 2,
  },
  {
    sourceName: "ELLO ASTY",
    sourceSeries: "ELLO ASTY",
    targetName: "NIV LEK",
    targetSeries: "NIV LEK",
    weight: 2,
  },
  {
    sourceName: "JESS",
    sourceSeries: "JESS",
    targetName: "YOLO ZIFF",
    targetSeries: "YOLO ZIFF",
    weight: 1,
  },
  {
    sourceName: "JESS",
    sourceSeries: "JESS",
    targetName: "POE",
    targetSeries: "POE",
    weight: 2,
  },
  {
    sourceName: "ELLO ASTY",
    sourceSeries: "ELLO ASTY",
    targetName: "JESS",
    targetSeries: "JESS",
    weight: 2,
  },
  {
    sourceName: "POE",
    sourceSeries: "POE",
    targetName: "YOLO ZIFF",
    targetSeries: "YOLO ZIFF",
    weight: 1,
  },
  {
    sourceName: "ELLO ASTY",
    sourceSeries: "ELLO ASTY",
    targetName: "YOLO ZIFF",
    targetSeries: "YOLO ZIFF",
    weight: 1,
  },
  {
    sourceName: "LEIA",
    sourceSeries: "LEIA",
    targetName: "REY",
    targetSeries: "REY",
    weight: 1,
  },
  {
    sourceName: "LUKE",
    sourceSeries: "LUKE",
    targetName: "REY",
    targetSeries: "REY",
    weight: 1,
  },
];
